modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="kraskaskas_mod"
version="1.0.0"
displayName="Kraskaska's Mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="alexe, MCreator"

[[dependencies.kraskaskas_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




